#!/usr/bin/env python3

import colors as c

import time

snake = '''

   _____             _        
  / ____|           | |       
 | (___  _ __   __ _| | _____ 
  \___ \| '_ \ / _` | |/ / _ \\
  ____) | | | | (_| |   <  __/
 |_____/|_| |_|\__,_|_|\_\___|
                              
 '''

c.clear_screen()

count_length = 0.387
  


for verse in range(5):

    for badger in range(12):
        print(c.green + 'Badger' + c.reset)
        time.sleep(count_length)

    for badger in range(2):
        print(c.red + 'Mushroom' + c.reset)
        time.sleep(count_length)

    c.clear_screen()

print(snake)
time.sleep(count_length * 10)

