#!/usr/bin/env python3

import colors as c

print(c.clear)
print(c.yellow + '''Who would cross the bridge of Death Must
answer me these questions three
'Ere the other side he see''' + c.reset)

name = input(c.green + 'what is your name? >')


answer1 = input(c.red + 'What is your quest? >')


if name in ['lancelot','galahad']:
    color = input(c.blue + 'What is your favorite color? > ')

