#!/usr/bin/env python3
import colors as c



while True:
    print(c.magenta + 'Rainbow' + c.red + 'Rainbow' + c.orange + 'Rainbow' + c.yellow + 'Rainbow' + c.green + 'Rainbow' + c.cyan + 'Rainbow' + c.blue + 'Rainbow' + c.violet + 'Rainbow'    ,end='')
