#!/usr/bin/env python3

import colors as c
import time

seconds = 0
hundredths = 0
minutes = 0
hours = 0
days = 0
weeks = 0
print(c.clear)
try:
    while True:
        time.sleep(0.01)
        print(c.clear)
        print(c.green + ' {} weeks {} days {}:{}:{}.{}'.format(weeks,days,hours,minutes,seconds,hundredths))
        '''
        print('minutes')
        print(minutes)
        print('seconds:')
        print(seconds)
        print('hundredths:')
        print(hundredths)
        '''

    if hundredths == 100:
        seconds += 1
        hundredths = 0
    if seconds == 60:
        minutes += 1
        seconds = 0
    if minutes == 60:
        hours += 1
        minutes = 0
    if hours == 60:
       minutes += 60 
       hours = 1
    if days == 24:
       hours += 24
       days = 1
    if weeks == 7:
       days += 7
       weeks = 1

except KeyboardInterrupt:
    exit()



