#!/usr/bin/env python3

import colors as c
import time

seconds = 0
hundredths = 0
minutes = 0
hours = 0
days = 0
weeks = 0



    while True:
    print(c.clear)
    print(c.orange + 'Weeks' + c.reset, end=': ')
    print(weeks)
    print(c.yellow + 'Days' + c.reset, end=': ')
    print(days)
    print(c.green + 'Hours' + c.reset, end=': ')
    print(hours)
    print(c.cyan + 'Minutes' + c.reset, end=': ')
    print(minutes)
    print(c.blue + 'Seconds' + c.reset, end=': ')
    print(seconds)
    print(c.magenta + 'Hundredths' + c.reset, end=': ')
    print(hundredths)
    time.sleep(0.01)
    hundredths += 1
    if hundredths == 100:
        seconds += 1
        hundredths = 0
    if seconds == 60:
        minutes += 1
        seconds = 0
    if minutes == 60:
        hours += 1
        minutes = 0
    if hours == 60:
       minutes += 60 
       hours = 1
    if days == 24:
       hours += 24
       days = 1
    if weeks == 7:
       days += 7
       weeks = 1
       


