#!/usr/bin/env python3

import colors as c
from utils import ask

print(c.clear)

print(c.orange + 'Do You Like Waffels?' + c.reset)

waffle = input(c.green + ' -->' + c.yellow + ' ')

if waffle == 'no':
    print(c.red + 'I LOVE WAFFELS YOU BUTT' + c.reset)

if waffle == 'yes':
    print(c.blue + 'Do You Like Pancakes?' + c.reset)

pancake = input(c.orange + '-->' + c.green + ' ')

if pancake == 'no':
    print(c.orange + 'I LOVE PANCAKES YOU BUTT' + c.reset)

if pancake == 'yes':
    print(c.yellow + 'Do You Like French Toast?' + c.reset)

frenchtoast = input(c.green + '-->' + c.blue + ' ')

if frenchtoast == 'no':
    print(c.yellow + 'I LOVE FRENCH TOAST YOU BUTT' + c.reset)

if frenchtoast == 'yes':
    print(c.green + ' If You Made It Here You Have Completed This Quiz And Life' + c.reset)



