#!/usr/bin/env python3

import colors as c
import time

print(c.clear)
while True:

    for count in range(12):
         print(c.orange + 'badgers')
         time.sleep(0.5)

    for count in range(2):
        print(c.blue + 'mushroom')
        time.sleep(0.8)

        
    for count in range (1): 
        print(c.clear)


