#!/usr/bin/env python3

import colors as c

print(c.clear)
print(c.green + 'Hi Whats Your Name?')
Name = input(c.yellow + 'Whats your name? --->' + c.pink )
print(c.red + "Nice to meet you " + c.blue + Name +"!")




