#!/usr/bin/env python3

import time
import colors as c

print(c.clear)

waffle = input(c.orange + 'Do you like waffles? --> ')

if waffle == 'yes':
    pancakes = input(c.red + 'Do you like pancakes? --> ')
   
    if pancakes == 'yes':
        frenchtoast = input(c.green + 'Do you like French Toast --> ')
        if frenchtoast == 'yes':
            print(c.blue + 'IM SO INVITING YOU TO BREKFAST!!!!!')
        
        elif frenchtoast == 'no':
            print(c.yellow + 'Well I like frenchtoast!!')
            time.sleep(.25)
            exit()
            
        else:
            print(c.violet + 'What?')
            time.sleep(.25)
            exit() 

    elif pancakes == 'no':
        print(c.pink + 'Well i like pancakes!!')
        time.sleep(.75)
        exit()

    else:
        print(c.violet + 'What?')
        time.sleep(.25)
        exit()
        

elif waffle == 'no':
    print(c.pink + 'Well I love waffles!!')
    time.sleep(.75)
    exit()

else:   
    print(c.violet + 'What?')  
    time.sleep(.25)
    exit()




